# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
version: 2

jobs:
  install:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - restore_cache:
          key: node_modules-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Fetch dependencies
          command: npm install
      - save_cache:
          key: node_modules-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: ./
          paths:
            - ./
  # Code static analysis.
  lint:
    docker:
      - image: circleci/node:lts
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Lint all frontend code
          command: |
            npm run lint
  # Build front-end assets.
#  build_assets:
#    docker:
#      - image: circleci/node:lts
#    steps:
#      - attach_workspace:
#          at: ./
#      - run:
#          name: Fetch dependencies
#          command: npm run build

  # Static analysis of any PHP/Drupal code.
  coding_standards:
    docker:
      - image: circleci/php:7.4.15-apache-browsers
    steps:
      - checkout
      - run:
          name: Fetch phpcs and dependencies
          command: |
            composer require drupal/coder --prefer-stable --no-interaction --optimize-autoloader
            # Move vendor directory up a level as we don't want to code-check all of that.
            mv vendor ../
      - run:
          name: Fetch phpcs convenience script
          command: |
            curl https://raw.githubusercontent.com/dof-dss/nidirect-drupal/main/phpcs.sh -o /home/circleci/project/phpcs.sh
            chmod +x /home/circleci/project/phpcs.sh
      - run:
          name: PHPCS analysis
          command: /home/circleci/project/phpcs.sh /home/circleci "/home/circleci/project"

  deprecated_code:
    docker:
      - image: circleci/php:7.4.15-apache-browsers
    steps:
      - checkout:
          path: /home/circleci/nicsdru_origins_theme
      - run:
          name: Add OS and PHP extensions/config
          command: |
            sudo cp /home/circleci/nicsdru_origins_theme/.circleci/docker-php-circleci.ini /usr/local/etc/php/conf.d/
            sudo apt --allow-releaseinfo-change update
            sudo apt install -y libpng-dev
            sudo docker-php-ext-install gd
      - run:
          name: Fetch latest Drupal version
          command: |
            cd /home/circleci
            composer create-project drupal-composer/drupal-project:8.x-dev /home/circleci/project --no-interaction
      - run:
          name: Download dependent contrib modules.
          command: |
            cd /home/circleci/project
            composer require mglaman/drupal-check --no-interaction
      - run:
          name: Move custom code into position
          command: mv /home/circleci/nicsdru_origins_theme /home/circleci/project/web/themes/custom
      - run:
          name: Deprecated code check
          command: |
            cd /home/circleci/project/web
            ../vendor/bin/drupal-check themes/custom -e "*/tests/*"

workflows:
  version: 2
  build-static-analysis:
    jobs:
      - install
      - lint:
          requires:
            - install
#      - build_assets:
#          requires:
#            - install
      - coding_standards
      - deprecated_code
